use_ddp: False   # whether to use DataDistributedParallel, for multi-gpus.
port:   # the port for the DataDistributedParallel training.

resume: /content/drive/MyDrive/2023학교/AIKU/2023_2_project2/mxfont-main/train_results/2023_12_24_02:35:04/checkpoints/last.pth
work_dir: /content/drive/MyDrive/2023학교/AIKU/2023_2_project2/mxfont-main/train_results   # the directory to save checkpoints, validation images, and the log.

decomposition: /content/drive/MyDrive/fewshot-font-generation-main/data/kor/decomposition.json   # path to the "decomposition rule" file.
primals: /content/drive/MyDrive/fewshot-font-generation-main/data/kor/primals.json   # path to the "primals" file.

dset:   # leave blank
  train:   # leave blank
    data_dir: /content/drive/MyDrive/2023학교/AIKU/2023_2_project2/mxfont-main/data/ttfs/train_jy_2   # path to .ttf files for the training
  val:   # leave blank
    data_dir: /content/drive/MyDrive/2023학교/AIKU/2023_2_project2/mxfont-main/data/ttfs/val   # path to .ttf files for the validation
    source_font: /content/drive/MyDrive/2023학교/AIKU/2023_2_project2/mxfont-main/data/ttfs/val/Jeongnimsaji-B.ttf   # path to the .ttf file used as the source font during the validation
